######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 29 15:01:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h block.h breakout.h paddle.h
SOURCES += ball.cpp block.cpp breakout.cpp main.cpp paddle.cpp
